const xlsx = require('xlsx');
const path = require('path');

// ===== ВСЕ 300 ВОПРОСОВ =====

const allQuestions = [
  // ==========================================
  // МЕДИЦИНА: 1-100
  // ==========================================
  { theme: 'Медицина', word: 'Scalpel', opt1: 'Шприц', opt2: 'Скальпель', opt3: 'Пинцет', opt4: 'Зажим', correct: 2 },
  { theme: 'Медицина', word: 'Emergency room', opt1: 'Операционная', opt2: 'Палата интенсивной терапии', opt3: 'Отделение неотложной помощи', opt4: 'Регистратура', correct: 3 },
  { theme: 'Медицина', word: 'Blood pressure', opt1: 'Давление крови', opt2: 'Артериальное давление', opt3: 'Пульс', opt4: 'Температура тела', correct: 2 },
  { theme: 'Медицина', word: 'Diagnosis', opt1: 'Лечение', opt2: 'Симптом', opt3: 'Рецепт', opt4: 'Диагноз', correct: 4 },
  { theme: 'Медицина', word: 'Prescription', opt1: 'Диагноз', opt2: 'Рецепт', opt3: 'Процедура', opt4: 'Анализ', correct: 2 },
  { theme: 'Медицина', word: 'Stethoscope', opt1: 'Термометр', opt2: 'Тонометр', opt3: 'Стетоскоп', opt4: 'Отоскоп', correct: 3 },
  { theme: 'Медицина', word: 'Syringe', opt1: 'Шприц', opt2: 'Игла', opt3: 'Катетер', opt4: 'Скальпель', correct: 1 },
  { theme: 'Медицина', word: 'Anesthesia', opt1: 'Антисептик', opt2: 'Анестезия', opt3: 'Анальгетик', opt4: 'Антибиотик', correct: 2 },
  { theme: 'Медицина', word: 'Cardiologist', opt1: 'Невролог', opt2: 'Кардиолог', opt3: 'Пульмонолог', opt4: 'Гастроэнтеролог', correct: 2 },
  { theme: 'Медицина', word: 'Inpatient', opt1: 'Амбулаторный пациент', opt2: 'Стационарный пациент', opt3: 'Экстренный пациент', opt4: 'Плановый пациент', correct: 2 },
  { theme: 'Медицина', word: 'Outpatient', opt1: 'Стационарный пациент', opt2: 'Амбулаторный пациент', opt3: 'Тяжёлый пациент', opt4: 'Послеоперационный пациент', correct: 2 },
  { theme: 'Медицина', word: 'Fracture', opt1: 'Ушиб', opt2: 'Растяжение', opt3: 'Перелом', opt4: 'Вывих', correct: 3 },
  { theme: 'Медицина', word: 'Concussion', opt1: 'Сотрясение мозга', opt2: 'Ушиб мозга', opt3: 'Перелом черепа', opt4: 'Кровоизлияние в мозг', correct: 1 },
  { theme: 'Медицина', word: 'Biopsy', opt1: 'Анализ крови', opt2: 'Биопсия', opt3: 'Вскрытие', opt4: 'Рентген', correct: 2 },
  { theme: 'Медицина', word: 'Chemotherapy', opt1: 'Лучевая терапия', opt2: 'Химиотерапия', opt3: 'Гормональная терапия', opt4: 'Иммунотерапия', correct: 2 },
  { theme: 'Медицина', word: 'Intensive Care Unit', opt1: 'Приёмное отделение', opt2: 'Отделение реанимации и интенсивной терапии', opt3: 'Хирургическое отделение', opt4: 'Терапевтическое отделение', correct: 2 },
  { theme: 'Медицина', word: 'Ventilator', opt1: 'Дефибриллятор', opt2: 'Кардиомонитор', opt3: 'Аппарат ИВЛ', opt4: 'Электрокардиограф', correct: 3 },
  { theme: 'Медицина', word: 'Tourniquet', opt1: 'Бинт', opt2: 'Шина', opt3: 'Жгут', opt4: 'Пластырь', correct: 3 },
  { theme: 'Медицина', word: 'Gauze', opt1: 'Марля', opt2: 'Вата', opt3: 'Бинт эластичный', opt4: 'Лейкопластырь', correct: 1 },
  { theme: 'Медицина', word: 'Suture', opt1: 'Разрез', opt2: 'Шов', opt3: 'Прокол', opt4: 'Дренаж', correct: 2 },
  { theme: 'Медицина', word: 'Inflammation', opt1: 'Инфекция', opt2: 'Воспаление', opt3: 'Кровотечение', opt4: 'Опухоль', correct: 2 },
  { theme: 'Медицина', word: 'Antibiotic', opt1: 'Антисептик', opt2: 'Противовирусное', opt3: 'Антибиотик', opt4: 'Противогрибковое', correct: 3 },
  { theme: 'Медицина', word: 'Vaccine', opt1: 'Лекарство', opt2: 'Сыворотка', opt3: 'Вакцина', opt4: 'Антидот', correct: 3 },
  { theme: 'Медицина', word: 'Dosage', opt1: 'Доза', opt2: 'Курс', opt3: 'Схема', opt4: 'Периодичность', correct: 1 },
  { theme: 'Медицина', word: 'Side effect', opt1: 'Противопоказание', opt2: 'Передозировка', opt3: 'Побочный эффект', opt4: 'Аллергическая реакция', correct: 3 },
  { theme: 'Медицина', word: 'Malignant tumor', opt1: 'Доброкачественная опухоль', opt2: 'Злокачественная опухоль', opt3: 'Киста', opt4: 'Метастаз', correct: 2 },
  { theme: 'Медицина', word: 'Benign tumor', opt1: 'Доброкачественная опухоль', opt2: 'Злокачественная опухоль', opt3: 'Карцинома', opt4: 'Саркома', correct: 1 },
  { theme: 'Медицина', word: 'Metastasis', opt1: 'Воспаление', opt2: 'Инфекция', opt3: 'Метастаз', opt4: 'Рецидив', correct: 3 },
  { theme: 'Медицина', word: 'Remission', opt1: 'Обострение', opt2: 'Рецидив', opt3: 'Осложнение', opt4: 'Ремиссия', correct: 4 },
  { theme: 'Медицина', word: 'Relapse', opt1: 'Ремиссия', opt2: 'Рецидив', opt3: 'Выздоровление', opt4: 'Профилактика', correct: 2 },
  { theme: 'Медицина', word: 'Prognosis', opt1: 'Диагноз', opt2: 'Анамнез', opt3: 'Прогноз', opt4: 'Эпикриз', correct: 3 },
  { theme: 'Медицина', word: 'Etiology', opt1: 'Этиология', opt2: 'Патогенез', opt3: 'Симптоматика', opt4: 'Эпидемиология', correct: 1 },
  { theme: 'Медицина', word: 'Pathogenesis', opt1: 'Этиология', opt2: 'Патогенез', opt3: 'Диагностика', opt4: 'Лечение', correct: 2 },
  { theme: 'Медицина', word: 'Palliative care', opt1: 'Интенсивная терапия', opt2: 'Паллиативная помощь', opt3: 'Профилактическая медицина', opt4: 'Реабилитация', correct: 2 },
  { theme: 'Медицина', word: 'Hospice', opt1: 'Больница', opt2: 'Поликлиника', opt3: 'Хоспис', opt4: 'Санаторий', correct: 3 },
  { theme: 'Медицина', word: 'Defibrillator', opt1: 'Кардиостимулятор', opt2: 'Дефибриллятор', opt3: 'Электрокардиограф', opt4: 'Пульсоксиметр', correct: 2 },
  { theme: 'Медицина', word: 'Pacemaker', opt1: 'Дефибриллятор', opt2: 'Кардиостимулятор', opt3: 'Стетоскоп', opt4: 'Тонометр', correct: 2 },
  { theme: 'Медицина', word: 'Hemorrhage', opt1: 'Гематома', opt2: 'Тромбоз', opt3: 'Кровоизлияние', opt4: 'Ишемия', correct: 3 },
  { theme: 'Медицина', word: 'Thrombosis', opt1: 'Эмболия', opt2: 'Тромбоз', opt3: 'Аневризма', opt4: 'Варикоз', correct: 2 },
  { theme: 'Медицина', word: 'Embolism', opt1: 'Тромбоз', opt2: 'Эмболия', opt3: 'Инфаркт', opt4: 'Инсульт', correct: 2 },
  { theme: 'Медицина', word: 'Aneurysm', opt1: 'Тромб', opt2: 'Бляшка', opt3: 'Аневризма', opt4: 'Стеноз', correct: 3 },
  { theme: 'Медицина', word: 'Ischemia', opt1: 'Некроз', opt2: 'Ишемия', opt3: 'Гипоксия', opt4: 'Атрофия', correct: 2 },
  { theme: 'Медицина', word: 'Necrosis', opt1: 'Апоптоз', opt2: 'Регенерация', opt3: 'Некроз', opt4: 'Гипертрофия', correct: 3 },
  { theme: 'Медицина', word: 'Edema', opt1: 'Отёк', opt2: 'Покраснение', opt3: 'Зуд', opt4: 'Сыпь', correct: 1 },
  { theme: 'Медицина', word: 'Sepsis', opt1: 'Аллергия', opt2: 'Интоксикация', opt3: 'Сепсис', opt4: 'Шок', correct: 3 },
  { theme: 'Медицина', word: 'Anaphylaxis', opt1: 'Крапивница', opt2: 'Отёк Квинке', opt3: 'Анафилаксия', opt4: 'Поллиноз', correct: 3 },
  { theme: 'Медицина', word: 'Placebo', opt1: 'Лекарство', opt2: 'Плацебо', opt3: 'Вакцина', opt4: 'Антидот', correct: 2 },
  { theme: 'Медицина', word: 'Clinical trial', opt1: 'Доклиническое исследование', opt2: 'Клиническое исследование', opt3: 'Мета-анализ', opt4: 'Систематический обзор', correct: 2 },
  { theme: 'Медицина', word: 'Informed consent', opt1: 'Медицинская карта', opt2: 'Страховой полис', opt3: 'Информированное согласие', opt4: 'Врачебная тайна', correct: 3 },
  { theme: 'Медицина', word: 'Medical history', opt1: 'Эпикриз', opt2: 'Анамнез', opt3: 'Диагноз', opt4: 'Рецепт', correct: 2 },
  { theme: 'Медицина', word: 'Hypertension', opt1: 'Гипотония', opt2: 'Гипертензия', opt3: 'Тахикардия', opt4: 'Аритмия', correct: 2 },
  { theme: 'Медицина', word: 'Hypotension', opt1: 'Гипертензия', opt2: 'Гипотония', opt3: 'Брадикардия', opt4: 'Стенокардия', correct: 2 },
  { theme: 'Медицина', word: 'Tachycardia', opt1: 'Брадикардия', opt2: 'Тахикардия', opt3: 'Аритмия', opt4: 'Экстрасистолия', correct: 2 },
  { theme: 'Медицина', word: 'Bradycardia', opt1: 'Тахикардия', opt2: 'Брадикардия', opt3: 'Гипертензия', opt4: 'Гипотония', correct: 2 },
  { theme: 'Медицина', word: 'Myocardial infarction', opt1: 'Инсульт', opt2: 'Инфаркт миокарда', opt3: 'Стенокардия', opt4: 'Перикардит', correct: 2 },
  { theme: 'Медицина', word: 'Stroke', opt1: 'Инфаркт', opt2: 'Инсульт', opt3: 'Эпилепсия', opt4: 'Мигрень', correct: 2 },
  { theme: 'Медицина', word: 'Epilepsy', opt1: 'Эпилепсия', opt2: 'Болезнь Паркинсона', opt3: 'Рассеянный склероз', opt4: 'Миастения', correct: 1 },
  { theme: 'Медицина', word: 'Parkinsons disease', opt1: 'Болезнь Альцгеймера', opt2: 'Болезнь Паркинсона', opt3: 'Эпилепсия', opt4: 'Деменция', correct: 2 },
  { theme: 'Медицина', word: 'Alzheimers disease', opt1: 'Болезнь Паркинсона', opt2: 'Болезнь Альцгеймера', opt3: 'Деменция', opt4: 'Шизофрения', correct: 2 },
  { theme: 'Медицина', word: 'Diabetes mellitus', opt1: 'Несахарный диабет', opt2: 'Сахарный диабет', opt3: 'Гипогликемия', opt4: 'Гипергликемия', correct: 2 },
  { theme: 'Медицина', word: 'Insulin', opt1: 'Глюкагон', opt2: 'Кортизол', opt3: 'Инсулин', opt4: 'Адреналин', correct: 3 },
  { theme: 'Медицина', word: 'Pneumonia', opt1: 'Бронхит', opt2: 'Пневмония', opt3: 'Туберкулёз', opt4: 'Астма', correct: 2 },
  { theme: 'Медицина', word: 'Tuberculosis', opt1: 'Пневмония', opt2: 'Туберкулёз', opt3: 'Бронхит', opt4: 'Эмфизема', correct: 2 },
  { theme: 'Медицина', word: 'Asthma', opt1: 'Аллергия', opt2: 'Бронхит', opt3: 'Астма', opt4: 'Пневмония', correct: 3 },
  { theme: 'Медицина', word: 'Bronchitis', opt1: 'Бронхит', opt2: 'Пневмония', opt3: 'Астма', opt4: 'Ларингит', correct: 1 },
  { theme: 'Медицина', word: 'Hepatitis', opt1: 'Панкреатит', opt2: 'Гепатит', opt3: 'Холецистит', opt4: 'Цирроз', correct: 2 },
  { theme: 'Медицина', word: 'Cirrhosis', opt1: 'Гепатит', opt2: 'Цирроз', opt3: 'Панкреатит', opt4: 'Холецистит', correct: 2 },
  { theme: 'Медицина', word: 'Pancreatitis', opt1: 'Гепатит', opt2: 'Панкреатит', opt3: 'Гастрит', opt4: 'Холецистит', correct: 2 },
  { theme: 'Медицина', word: 'Gastritis', opt1: 'Гастрит', opt2: 'Язва', opt3: 'Панкреатит', opt4: 'Колит', correct: 1 },
  { theme: 'Медицина', word: 'Ulcer', opt1: 'Гастрит', opt2: 'Язва', opt3: 'Эрозия', opt4: 'Полип', correct: 2 },
  { theme: 'Медицина', word: 'Appendicitis', opt1: 'Аппендицит', opt2: 'Перитонит', opt3: 'Холецистит', opt4: 'Дивертикулит', correct: 1 },
  { theme: 'Медицина', word: 'Peritonitis', opt1: 'Аппендицит', opt2: 'Перитонит', opt3: 'Панкреатит', opt4: 'Гастрит', correct: 2 },
  { theme: 'Медицина', word: 'Meningitis', opt1: 'Энцефалит', opt2: 'Менингит', opt3: 'Неврит', opt4: 'Радикулит', correct: 2 },
  { theme: 'Медицина', word: 'Encephalitis', opt1: 'Менингит', opt2: 'Энцефалит', opt3: 'Инсульт', opt4: 'Абсцесс', correct: 2 },
  { theme: 'Медицина', word: 'Abscess', opt1: 'Флегмона', opt2: 'Абсцесс', opt3: 'Фурункул', opt4: 'Карбункул', correct: 2 },
  { theme: 'Медицина', word: 'Laparoscopy', opt1: 'Лапаротомия', opt2: 'Лапароскопия', opt3: 'Торакоскопия', opt4: 'Колоноскопия', correct: 2 },
  { theme: 'Медицина', word: 'Endoscopy', opt1: 'Эндоскопия', opt2: 'Колоноскопия', opt3: 'Гастроскопия', opt4: 'Бронхоскопия', correct: 1 },
  { theme: 'Медицина', word: 'Colonoscopy', opt1: 'Гастроскопия', opt2: 'Колоноскопия', opt3: 'Цистоскопия', opt4: 'Лапароскопия', correct: 2 },
  { theme: 'Медицина', word: 'Mammography', opt1: 'УЗИ молочных желёз', opt2: 'Маммография', opt3: 'Биопсия молочной железы', opt4: 'Термография', correct: 2 },
  { theme: 'Медицина', word: 'Ultrasound', opt1: 'Рентген', opt2: 'МРТ', opt3: 'Ультразвуковое исследование', opt4: 'КТ', correct: 3 },
  { theme: 'Медицина', word: 'MRI (Magnetic Resonance Imaging)', opt1: 'Компьютерная томография', opt2: 'Магнитно-резонансная томография', opt3: 'Позитронно-эмиссионная томография', opt4: 'Рентгенография', correct: 2 },
  { theme: 'Медицина', word: 'CT scan', opt1: 'МРТ', opt2: 'Компьютерная томография', opt3: 'УЗИ', opt4: 'ПЭТ', correct: 2 },
  { theme: 'Медицина', word: 'X-ray', opt1: 'УЗИ', opt2: 'Рентген', opt3: 'МРТ', opt4: 'КТ', correct: 2 },
  { theme: 'Медицина', word: 'Complete blood count', opt1: 'Биохимический анализ крови', opt2: 'Общий анализ крови', opt3: 'Коагулограмма', opt4: 'Липидограмма', correct: 2 },
  { theme: 'Медицина', word: 'Urinalysis', opt1: 'Анализ крови', opt2: 'Анализ мочи', opt3: 'Анализ кала', opt4: 'Бакпосев', correct: 2 },
  { theme: 'Медицина', word: 'Catheter', opt1: 'Зонд', opt2: 'Катетер', opt3: 'Дренаж', opt4: 'Шунт', correct: 2 },
  { theme: 'Медицина', word: 'Intravenous drip', opt1: 'Внутримышечная инъекция', opt2: 'Подкожная инъекция', opt3: 'Внутривенная капельница', opt4: 'Пероральный приём', correct: 3 },
  { theme: 'Медицина', word: 'Transplant', opt1: 'Имплантат', opt2: 'Трансплантат', opt3: 'Протез', opt4: 'Шунт', correct: 2 },
  { theme: 'Медицина', word: 'Prosthesis', opt1: 'Трансплантат', opt2: 'Протез', opt3: 'Имплантат', opt4: 'Ортез', correct: 2 },
  { theme: 'Медицина', word: 'Amputation', opt1: 'Резекция', opt2: 'Ампутация', opt3: 'Трепанация', opt4: 'Пункция', correct: 2 },
  { theme: 'Медицина', word: 'Resection', opt1: 'Ампутация', opt2: 'Резекция', opt3: 'Трансплантация', opt4: 'Имплантация', correct: 2 },
  { theme: 'Медицина', word: 'Cesarean section', opt1: 'Эпизиотомия', opt2: 'Кесарево сечение', opt3: 'Гистерэктомия', opt4: 'Лапаротомия', correct: 2 },
  { theme: 'Медицина', word: 'Prenatal care', opt1: 'Послеродовой уход', opt2: 'Дородовой уход', opt3: 'Неонатальный уход', opt4: 'Педиатрический уход', correct: 2 },
  { theme: 'Медицина', word: 'Pediatrics', opt1: 'Гериатрия', opt2: 'Педиатрия', opt3: 'Неонатология', opt4: 'Терапия', correct: 2 },
  { theme: 'Медицина', word: 'Geriatrics', opt1: 'Педиатрия', opt2: 'Гериатрия', opt3: 'Терапия', opt4: 'Неврология', correct: 2 },
  { theme: 'Медицина', word: 'Oncology', opt1: 'Онкология', opt2: 'Гематология', opt3: 'Иммунология', opt4: 'Радиология', correct: 1 },
  { theme: 'Медицина', word: 'Dermatology', opt1: 'Неврология', opt2: 'Дерматология', opt3: 'Аллергология', opt4: 'Ревматология', correct: 2 },
  { theme: 'Медицина', word: 'Ophthalmology', opt1: 'Отоларингология', opt2: 'Офтальмология', opt3: 'Стоматология', opt4: 'Неврология', correct: 2 },
  { theme: 'Медицина', word: 'Otolaryngology', opt1: 'Офтальмология', opt2: 'Отоларингология', opt3: 'Пульмонология', opt4: 'Кардиология', correct: 2 },
  { theme: 'Медицина', word: 'Rheumatology', opt1: 'Ревматология', opt2: 'Ортопедия', opt3: 'Травматология', opt4: 'Неврология', correct: 1 },

  // ==========================================
  // ИНЖЕНЕРИЯ: 101-200
  // ==========================================
  { theme: 'Инженерия', word: 'Gearbox', opt1: 'Коробка передач', opt2: 'Двигатель', opt3: 'Тормозная система', opt4: 'Сцепление', correct: 1 },
  { theme: 'Инженерия', word: 'Circuit board', opt1: 'Электрическая схема', opt2: 'Печатная плата', opt3: 'Проводка', opt4: 'Трансформатор', correct: 2 },
  { theme: 'Инженерия', word: 'Torque wrench', opt1: 'Разводной ключ', opt2: 'Динамометрический ключ', opt3: 'Отвёртка', opt4: 'Дрель', correct: 2 },
  { theme: 'Инженерия', word: 'Load bearing capacity', opt1: 'Грузоподъёмность', opt2: 'Скорость вращения', opt3: 'Несущая способность', opt4: 'Крутящий момент', correct: 3 },
  { theme: 'Инженерия', word: 'Welding', opt1: 'Пайка', opt2: 'Сварка', opt3: 'Клёпка', opt4: 'Склеивание', correct: 2 },
  { theme: 'Инженерия', word: 'Soldering', opt1: 'Сварка', opt2: 'Пайка', opt3: 'Шлифовка', opt4: 'Сверление', correct: 2 },
  { theme: 'Инженерия', word: 'Riveting', opt1: 'Сварка', opt2: 'Клёпка', opt3: 'Пайка', opt4: 'Болтовое соединение', correct: 2 },
  { theme: 'Инженерия', word: 'Actuator', opt1: 'Датчик', opt2: 'Исполнительный механизм', opt3: 'Контроллер', opt4: 'Регулятор', correct: 2 },
  { theme: 'Инженерия', word: 'Sensor', opt1: 'Исполнительный механизм', opt2: 'Датчик', opt3: 'Контроллер', opt4: 'Реле', correct: 2 },
  { theme: 'Инженерия', word: 'Controller', opt1: 'Датчик', opt2: 'Исполнительный механизм', opt3: 'Контроллер', opt4: 'Трансмиттер', correct: 3 },
  { theme: 'Инженерия', word: 'Bearing', opt1: 'Подшипник', opt2: 'Вал', opt3: 'Шестерня', opt4: 'Муфта', correct: 1 },
  { theme: 'Инженерия', word: 'Shaft', opt1: 'Подшипник', opt2: 'Вал', opt3: 'Втулка', opt4: 'Ось', correct: 2 },
  { theme: 'Инженерия', word: 'Coupling', opt1: 'Подшипник', opt2: 'Шестерня', opt3: 'Муфта', opt4: 'Тормоз', correct: 3 },
  { theme: 'Инженерия', word: 'Clutch', opt1: 'Сцепление', opt2: 'Тормоз', opt3: 'Коробка передач', opt4: 'Дифференциал', correct: 1 },
  { theme: 'Инженерия', word: 'Brake caliper', opt1: 'Тормозной диск', opt2: 'Тормозной суппорт', opt3: 'Тормозная колодка', opt4: 'Тормозной цилиндр', correct: 2 },
  { theme: 'Инженерия', word: 'Shock absorber', opt1: 'Пружина', opt2: 'Амортизатор', opt3: 'Стабилизатор', opt4: 'Рычаг подвески', correct: 2 },
  { theme: 'Инженерия', word: 'Torsion bar', opt1: 'Пружина', opt2: 'Торсион', opt3: 'Рессора', opt4: 'Амортизатор', correct: 2 },
  { theme: 'Инженерия', word: 'Crankshaft', opt1: 'Распределительный вал', opt2: 'Коленчатый вал', opt3: 'Карданный вал', opt4: 'Приводной вал', correct: 2 },
  { theme: 'Инженерия', word: 'Camshaft', opt1: 'Коленчатый вал', opt2: 'Распределительный вал', opt3: 'Карданный вал', opt4: 'Промежуточный вал', correct: 2 },
  { theme: 'Инженерия', word: 'Piston', opt1: 'Поршень', opt2: 'Цилиндр', opt3: 'Клапан', opt4: 'Шатун', correct: 1 },
  { theme: 'Инженерия', word: 'Cylinder head', opt1: 'Блок цилиндров', opt2: 'Головка блока цилиндров', opt3: 'Картер', opt4: 'Коллектор', correct: 2 },
  { theme: 'Инженерия', word: 'Gasket', opt1: 'Прокладка', opt2: 'Сальник', opt3: 'Уплотнитель', opt4: 'Манжета', correct: 1 },
  { theme: 'Инженерия', word: 'Seal', opt1: 'Прокладка', opt2: 'Сальник', opt3: 'Шпонка', opt4: 'Штифт', correct: 2 },
  { theme: 'Инженерия', word: 'O-ring', opt1: 'Плоская прокладка', opt2: 'Уплотнительное кольцо', opt3: 'Сальник', opt4: 'Манжета', correct: 2 },
  { theme: 'Инженерия', word: 'Thread', opt1: 'Резьба', opt2: 'Канавка', opt3: 'Фаска', opt4: 'Проточка', correct: 1 },
  { theme: 'Инженерия', word: 'Bolt', opt1: 'Винт', opt2: 'Болт', opt3: 'Шпилька', opt4: 'Заклёпка', correct: 2 },
  { theme: 'Инженерия', word: 'Nut', opt1: 'Болт', opt2: 'Гайка', opt3: 'Шайба', opt4: 'Шплинт', correct: 2 },
  { theme: 'Инженерия', word: 'Washer', opt1: 'Гайка', opt2: 'Шайба', opt3: 'Шпонка', opt4: 'Штифт', correct: 2 },
  { theme: 'Инженерия', word: 'Spring', opt1: 'Рессора', opt2: 'Пружина', opt3: 'Торсион', opt4: 'Демпфер', correct: 2 },
  { theme: 'Инженерия', word: 'Damper', opt1: 'Пружина', opt2: 'Демпфер', opt3: 'Торсион', opt4: 'Амортизатор', correct: 2 },
  { theme: 'Инженерия', word: 'Gear', opt1: 'Шестерня', opt2: 'Вал', opt3: 'Муфта', opt4: 'Шкив', correct: 1 },
  { theme: 'Инженерия', word: 'Sprocket', opt1: 'Шестерня', opt2: 'Звёздочка', opt3: 'Шкив', opt4: 'Маховик', correct: 2 },
  { theme: 'Инженерия', word: 'Pulley', opt1: 'Шкив', opt2: 'Звёздочка', opt3: 'Шестерня', opt4: 'Барабан', correct: 1 },
  { theme: 'Инженерия', word: 'Flywheel', opt1: 'Шкив', opt2: 'Маховик', opt3: 'Звёздочка', opt4: 'Ротор', correct: 2 },
  { theme: 'Инженерия', word: 'Rotor', opt1: 'Статор', opt2: 'Ротор', opt3: 'Якорь', opt4: 'Индуктор', correct: 2 },
  { theme: 'Инженерия', word: 'Stator', opt1: 'Статор', opt2: 'Ротор', opt3: 'Якорь', opt4: 'Коллектор', correct: 1 },
  { theme: 'Инженерия', word: 'Armature', opt1: 'Статор', opt2: 'Ротор', opt3: 'Якорь', opt4: 'Индуктор', correct: 3 },
  { theme: 'Инженерия', word: 'Commutator', opt1: 'Статор', opt2: 'Коллектор', opt3: 'Ротор', opt4: 'Щётка', correct: 2 },
  { theme: 'Инженерия', word: 'Brush', opt1: 'Коллектор', opt2: 'Щётка', opt3: 'Якорь', opt4: 'Статор', correct: 2 },
  { theme: 'Инженерия', word: 'Relay', opt1: 'Реле', opt2: 'Контактор', opt3: 'Предохранитель', opt4: 'Выключатель', correct: 1 },
  { theme: 'Инженерия', word: 'Contactor', opt1: 'Реле', opt2: 'Контактор', opt3: 'Автоматический выключатель', opt4: 'Рубильник', correct: 2 },
  { theme: 'Инженерия', word: 'Circuit breaker', opt1: 'Предохранитель', opt2: 'Автоматический выключатель', opt3: 'Реле', opt4: 'Контактор', correct: 2 },
  { theme: 'Инженерия', word: 'Fuse', opt1: 'Автоматический выключатель', opt2: 'Предохранитель', opt3: 'Реле', opt4: 'Контактор', correct: 2 },
  { theme: 'Инженерия', word: 'Transformer', opt1: 'Выпрямитель', opt2: 'Трансформатор', opt3: 'Инвертор', opt4: 'Стабилизатор', correct: 2 },
  { theme: 'Инженерия', word: 'Rectifier', opt1: 'Трансформатор', opt2: 'Выпрямитель', opt3: 'Инвертор', opt4: 'Конвертер', correct: 2 },
  { theme: 'Инженерия', word: 'Inverter', opt1: 'Трансформатор', opt2: 'Инвертор', opt3: 'Выпрямитель', opt4: 'Стабилизатор', correct: 2 },
  { theme: 'Инженерия', word: 'Capacitor', opt1: 'Резистор', opt2: 'Конденсатор', opt3: 'Катушка индуктивности', opt4: 'Диод', correct: 2 },
  { theme: 'Инженерия', word: 'Resistor', opt1: 'Резистор', opt2: 'Конденсатор', opt3: 'Транзистор', opt4: 'Диод', correct: 1 },
  { theme: 'Инженерия', word: 'Inductor', opt1: 'Конденсатор', opt2: 'Катушка индуктивности', opt3: 'Резистор', opt4: 'Трансформатор', correct: 2 },
  { theme: 'Инженерия', word: 'Diode', opt1: 'Транзистор', opt2: 'Диод', opt3: 'Резистор', opt4: 'Тиристор', correct: 2 },
  { theme: 'Инженерия', word: 'Transistor', opt1: 'Диод', opt2: 'Транзистор', opt3: 'Тиристор', opt4: 'Симистор', correct: 2 },
  { theme: 'Инженерия', word: 'Thyristor', opt1: 'Транзистор', opt2: 'Тиристор', opt3: 'Диод', opt4: 'Симистор', correct: 2 },
  { theme: 'Инженерия', word: 'Microcontroller', opt1: 'Микропроцессор', opt2: 'Микроконтроллер', opt3: 'ПЛИС', opt4: 'ЦСП', correct: 2 },
  { theme: 'Инженерия', word: 'Microprocessor', opt1: 'Микропроцессор', opt2: 'Микроконтроллер', opt3: 'Чипсет', opt4: 'Сопроцессор', correct: 1 },
  { theme: 'Инженерия', word: 'Firmware', opt1: 'Аппаратное обеспечение', opt2: 'Программное обеспечение', opt3: 'Встроенное программное обеспечение', opt4: 'Драйвер', correct: 3 },
  { theme: 'Инженерия', word: 'Feedback', opt1: 'Прямая связь', opt2: 'Обратная связь', opt3: 'Перекрёстная связь', opt4: 'Задержка', correct: 2 },
  { theme: 'Инженерия', word: 'PID controller', opt1: 'ПИД-регулятор', opt2: 'ПЛК', opt3: 'Микроконтроллер', opt4: 'Сервоусилитель', correct: 1 },
  { theme: 'Инженерия', word: 'PLC', opt1: 'ПИД-регулятор', opt2: 'Программируемый логический контроллер', opt3: 'Микроконтроллер', opt4: 'Серводрайв', correct: 2 },
  { theme: 'Инженерия', word: 'Servomotor', opt1: 'Шаговый двигатель', opt2: 'Серводвигатель', opt3: 'Асинхронный двигатель', opt4: 'Коллекторный двигатель', correct: 2 },
  { theme: 'Инженерия', word: 'Stepper motor', opt1: 'Серводвигатель', opt2: 'Шаговый двигатель', opt3: 'Линейный двигатель', opt4: 'Вентильный двигатель', correct: 2 },
  { theme: 'Инженерия', word: 'Hydraulic pump', opt1: 'Гидравлический насос', opt2: 'Гидромотор', opt3: 'Гидроцилиндр', opt4: 'Гидрораспределитель', correct: 1 },
  { theme: 'Инженерия', word: 'Hydraulic cylinder', opt1: 'Гидронасос', opt2: 'Гидроцилиндр', opt3: 'Гидромотор', opt4: 'Гидроаккумулятор', correct: 2 },
  { theme: 'Инженерия', word: 'Pneumatic valve', opt1: 'Гидравлический клапан', opt2: 'Пневматический клапан', opt3: 'Электромагнитный клапан', opt4: 'Обратный клапан', correct: 2 },
  { theme: 'Инженерия', word: 'Solenoid valve', opt1: 'Пневматический клапан', opt2: 'Электромагнитный клапан', opt3: 'Гидравлический клапан', opt4: 'Дроссельный клапан', correct: 2 },
  { theme: 'Инженерия', word: 'Check valve', opt1: 'Обратный клапан', opt2: 'Предохранительный клапан', opt3: 'Редукционный клапан', opt4: 'Запорный клапан', correct: 1 },
  { theme: 'Инженерия', word: 'Pressure relief valve', opt1: 'Обратный клапан', opt2: 'Предохранительный клапан', opt3: 'Редукционный клапан', opt4: 'Дроссель', correct: 2 },
  { theme: 'Инженерия', word: 'Heat exchanger', opt1: 'Радиатор', opt2: 'Теплообменник', opt3: 'Конденсатор', opt4: 'Испаритель', correct: 2 },
  { theme: 'Инженерия', word: 'Radiator', opt1: 'Радиатор', opt2: 'Теплообменник', opt3: 'Интеркулер', opt4: 'Масляный кулер', correct: 1 },
  { theme: 'Инженерия', word: 'Thermostat', opt1: 'Термопара', opt2: 'Термостат', opt3: 'Термистор', opt4: 'Термометр', correct: 2 },
  { theme: 'Инженерия', word: 'Thermocouple', opt1: 'Термостат', opt2: 'Термопара', opt3: 'Термистор', opt4: 'Термометр сопротивления', correct: 2 },
  { theme: 'Инженерия', word: 'Strain gauge', opt1: 'Тензодатчик', opt2: 'Акселерометр', opt3: 'Гироскоп', opt4: 'Датчик давления', correct: 1 },
  { theme: 'Инженерия', word: 'Accelerometer', opt1: 'Тензодатчик', opt2: 'Акселерометр', opt3: 'Гироскоп', opt4: 'Энкодер', correct: 2 },
  { theme: 'Инженерия', word: 'Gyroscope', opt1: 'Акселерометр', opt2: 'Гироскоп', opt3: 'Магнитометр', opt4: 'Барометр', correct: 2 },
  { theme: 'Инженерия', word: 'Encoder', opt1: 'Декодер', opt2: 'Энкодер', opt3: 'Мультиплексор', opt4: 'Демультиплексор', correct: 2 },
  { theme: 'Инженерия', word: 'Conveyor belt', opt1: 'Конвейерная лента', opt2: 'Приводной ремень', opt3: 'Цепной привод', opt4: 'Роликовый транспортёр', correct: 1 },
  { theme: 'Инженерия', word: 'CNC machine', opt1: '3D-принтер', opt2: 'Станок с ЧПУ', opt3: 'Фрезерный станок', opt4: 'Токарный станок', correct: 2 },
  { theme: 'Инженерия', word: 'Lathe', opt1: 'Фрезерный станок', opt2: 'Токарный станок', opt3: 'Шлифовальный станок', opt4: 'Сверлильный станок', correct: 2 },
  { theme: 'Инженерия', word: 'Milling machine', opt1: 'Токарный станок', opt2: 'Фрезерный станок', opt3: 'Строгальный станок', opt4: 'Долбёжный станок', correct: 2 },
  { theme: 'Инженерия', word: 'Tolerance', opt1: 'Посадка', opt2: 'Допуск', opt3: 'Зазор', opt4: 'Натяг', correct: 2 },
  { theme: 'Инженерия', word: 'Clearance', opt1: 'Зазор', opt2: 'Натяг', opt3: 'Допуск', opt4: 'Посадка', correct: 1 },
  { theme: 'Инженерия', word: 'Interference fit', opt1: 'Зазор', opt2: 'Посадка с натягом', opt3: 'Переходная посадка', opt4: 'Скользящая посадка', correct: 2 },
  { theme: 'Инженерия', word: 'Blueprint', opt1: 'Спецификация', opt2: 'Чертёж', opt3: 'Схема', opt4: 'Эскиз', correct: 2 },
  { theme: 'Инженерия', word: 'Schematic', opt1: 'Чертёж', opt2: 'Схема', opt3: 'Спецификация', opt4: 'Сборочный чертёж', correct: 2 },
  { theme: 'Инженерия', word: 'Specification', opt1: 'Чертёж', opt2: 'Спецификация', opt3: 'Смета', opt4: 'Техническое задание', correct: 2 },
  { theme: 'Инженерия', word: 'Bill of materials', opt1: 'Смета', opt2: 'Спецификация материалов', opt3: 'Ведомость', opt4: 'Накладная', correct: 2 },
  { theme: 'Инженерия', word: 'Prototype', opt1: 'Опытный образец', opt2: 'Макет', opt3: 'Модель', opt4: 'Чертёж', correct: 1 },
  { theme: 'Инженерия', word: 'Mockup', opt1: 'Прототип', opt2: 'Макет', opt3: 'Модель', opt4: 'Чертёж', correct: 2 },
  { theme: 'Инженерия', word: 'Finite element analysis', opt1: 'Анализ размерных цепей', opt2: 'Анализ методом конечных элементов', opt3: 'Кинематический анализ', opt4: 'Динамический анализ', correct: 2 },
  { theme: 'Инженерия', word: 'CFD', opt1: 'Метод конечных элементов', opt2: 'Вычислительная гидродинамика', opt3: 'Термодинамический анализ', opt4: 'Аэродинамический расчёт', correct: 2 },
  { theme: 'Инженерия', word: 'Corrosion', opt1: 'Эрозия', opt2: 'Коррозия', opt3: 'Износ', opt4: 'Усталость', correct: 2 },
  { theme: 'Инженерия', word: 'Fatigue', opt1: 'Износ', opt2: 'Усталость', opt3: 'Коррозия', opt4: 'Ползучесть', correct: 2 },
  { theme: 'Инженерия', word: 'Creep', opt1: 'Усталость', opt2: 'Износ', opt3: 'Ползучесть', opt4: 'Коррозия', correct: 3 },
  { theme: 'Инженерия', word: 'Yield strength', opt1: 'Предел прочности', opt2: 'Предел текучести', opt3: 'Твёрдость', opt4: 'Упругость', correct: 2 },
  { theme: 'Инженерия', word: 'Tensile strength', opt1: 'Предел текучести', opt2: 'Предел прочности на растяжение', opt3: 'Твёрдость', opt4: 'Пластичность', correct: 2 },
  { theme: 'Инженерия', word: 'Hardness', opt1: 'Прочность', opt2: 'Твёрдость', opt3: 'Пластичность', opt4: 'Упругость', correct: 2 },
  { theme: 'Инженерия', word: 'Ductility', opt1: 'Твёрдость', opt2: 'Пластичность', opt3: 'Хрупкость', opt4: 'Упругость', correct: 2 },
  { theme: 'Инженерия', word: 'Brittleness', opt1: 'Пластичность', opt2: 'Хрупкость', opt3: 'Твёрдость', opt4: 'Вязкость', correct: 2 },
  { theme: 'Инженерия', word: 'Toughness', opt1: 'Твёрдость', opt2: 'Вязкость', opt3: 'Прочность', opt4: 'Пластичность', correct: 2 },

  // ==========================================
  // СТРОИТЕЛЬСТВО: 201-300
  // ==========================================
  { theme: 'Строительство', word: 'Scaffolding', opt1: 'Фундамент', opt2: 'Строительные леса', opt3: 'Кровля', opt4: 'Арматура', correct: 2 },
  { theme: 'Строительство', word: 'Reinforced concrete', opt1: 'Пенобетон', opt2: 'Газобетон', opt3: 'Железобетон', opt4: 'Керамзитобетон', correct: 3 },
  { theme: 'Строительство', word: 'Blueprint', opt1: 'Смета', opt2: 'Чертёж', opt3: 'Макет', opt4: 'Спецификация', correct: 2 },
  { theme: 'Строительство', word: 'Masonry', opt1: 'Штукатурка', opt2: 'Малярные работы', opt3: 'Кирпичная кладка', opt4: 'Стяжка пола', correct: 3 },
  { theme: 'Строительство', word: 'Foundation', opt1: 'Фундамент', opt2: 'Цоколь', opt3: 'Перекрытие', opt4: 'Отмостка', correct: 1 },
  { theme: 'Строительство', word: 'Footing', opt1: 'Стена', opt2: 'Фундаментная подушка', opt3: 'Колонна', opt4: 'Балка', correct: 2 },
  { theme: 'Строительство', word: 'Pile', opt1: 'Свая', opt2: 'Столб', opt3: 'Колонна', opt4: 'Балка', correct: 1 },
  { theme: 'Строительство', word: 'Slab', opt1: 'Балка', opt2: 'Плита', opt3: 'Панель', opt4: 'Блок', correct: 2 },
  { theme: 'Строительство', word: 'Beam', opt1: 'Колонна', opt2: 'Балка', opt3: 'Ферма', opt4: 'Арка', correct: 2 },
  { theme: 'Строительство', word: 'Column', opt1: 'Балка', opt2: 'Колонна', opt3: 'Свая', opt4: 'Стойка', correct: 2 },
  { theme: 'Строительство', word: 'Truss', opt1: 'Балка', opt2: 'Ферма', opt3: 'Арка', opt4: 'Рама', correct: 2 },
  { theme: 'Строительство', word: 'Arch', opt1: 'Ферма', opt2: 'Арка', opt3: 'Свод', opt4: 'Купол', correct: 2 },
  { theme: 'Строительство', word: 'Vault', opt1: 'Арка', opt2: 'Свод', opt3: 'Купол', opt4: 'Перекрытие', correct: 2 },
  { theme: 'Строительство', word: 'Dome', opt1: 'Свод', opt2: 'Купол', opt3: 'Арка', opt4: 'Шпиль', correct: 2 },
  { theme: 'Строительство', word: 'Lintel', opt1: 'Подоконник', opt2: 'Перемычка', opt3: 'Откос', opt4: 'Порог', correct: 2 },
  { theme: 'Строительство', word: 'Joist', opt1: 'Балка перекрытия', opt2: 'Стропило', opt3: 'Прогон', opt4: 'Обрешётка', correct: 1 },
  { theme: 'Строительство', word: 'Rafter', opt1: 'Балка', opt2: 'Стропило', opt3: 'Прогон', opt4: 'Мауэрлат', correct: 2 },
  { theme: 'Строительство', word: 'Purlin', opt1: 'Стропило', opt2: 'Прогон', opt3: 'Обрешётка', opt4: 'Конёк', correct: 2 },
  { theme: 'Строительство', word: 'Batten', opt1: 'Прогон', opt2: 'Обрешётка', opt3: 'Стропило', opt4: 'Контробрешётка', correct: 2 },
  { theme: 'Строительство', word: 'Ridge', opt1: 'Карниз', opt2: 'Конёк', opt3: 'Фронтон', opt4: 'Ендова', correct: 2 },
  { theme: 'Строительство', word: 'Eaves', opt1: 'Карниз', opt2: 'Конёк', opt3: 'Фронтон', opt4: 'Свес', correct: 1 },
  { theme: 'Строительство', word: 'Gable', opt1: 'Карниз', opt2: 'Фронтон', opt3: 'Конёк', opt4: 'Ендова', correct: 2 },
  { theme: 'Строительство', word: 'Dormer', opt1: 'Мансардное окно', opt2: 'Слуховое окно', opt3: 'Эркер', opt4: 'Фрамуга', correct: 1 },
  { theme: 'Строительство', word: 'Flashing', opt1: 'Водосток', opt2: 'Гидроизоляционный фартук', opt3: 'Карнизная планка', opt4: 'Коньковая планка', correct: 2 },
  { theme: 'Строительство', word: 'Gutter', opt1: 'Водосточный жёлоб', opt2: 'Водосточная труба', opt3: 'Воронка', opt4: 'Отлив', correct: 1 },
  { theme: 'Строительство', word: 'Downspout', opt1: 'Жёлоб', opt2: 'Водосточная труба', opt3: 'Воронка', opt4: 'Отлив', correct: 2 },
  { theme: 'Строительство', word: 'Soffit', opt1: 'Карниз', opt2: 'Подшивка карниза', opt3: 'Фасад', opt4: 'Цоколь', correct: 2 },
  { theme: 'Строительство', word: 'Fascia', opt1: 'Подшивка', opt2: 'Лобовая доска', opt3: 'Карниз', opt4: 'Наличник', correct: 2 },
  { theme: 'Строительство', word: 'Siding', opt1: 'Штукатурка', opt2: 'Обшивка фасада', opt3: 'Кирпичная кладка', opt4: 'Облицовка', correct: 2 },
  { theme: 'Строительство', word: 'Cladding', opt1: 'Обшивка', opt2: 'Облицовка', opt3: 'Штукатурка', opt4: 'Утеплитель', correct: 2 },
  { theme: 'Строительство', word: 'Drywall', opt1: 'Гипсокартон', opt2: 'Фанера', opt3: 'ОСП', opt4: 'ДСП', correct: 1 },
  { theme: 'Строительство', word: 'Plywood', opt1: 'Гипсокартон', opt2: 'Фанера', opt3: 'ДСП', opt4: 'МДФ', correct: 2 },
  { theme: 'Строительство', word: 'Particle board', opt1: 'Фанера', opt2: 'Древесно-стружечная плита', opt3: 'МДФ', opt4: 'ОСП', correct: 2 },
  { theme: 'Строительство', word: 'OSB', opt1: 'Фанера', opt2: 'Ориентированно-стружечная плита', opt3: 'ДСП', opt4: 'МДФ', correct: 2 },
  { theme: 'Строительство', word: 'Insulation', opt1: 'Гидроизоляция', opt2: 'Теплоизоляция', opt3: 'Звукоизоляция', opt4: 'Пароизоляция', correct: 2 },
  { theme: 'Строительство', word: 'Vapor barrier', opt1: 'Гидроизоляция', opt2: 'Пароизоляция', opt3: 'Теплоизоляция', opt4: 'Ветрозащита', correct: 2 },
  { theme: 'Строительство', word: 'Waterproofing', opt1: 'Пароизоляция', opt2: 'Гидроизоляция', opt3: 'Теплоизоляция', opt4: 'Звукоизоляция', correct: 2 },
  { theme: 'Строительство', word: 'Sealant', opt1: 'Клей', opt2: 'Герметик', opt3: 'Мастика', opt4: 'Затирка', correct: 2 },
  { theme: 'Строительство', word: 'Caulk', opt1: 'Герметик', opt2: 'Шпатлёвка', opt3: 'Затирка', opt4: 'Мастика', correct: 1 },
  { theme: 'Строительство', word: 'Grout', opt1: 'Герметик', opt2: 'Затирка', opt3: 'Шпатлёвка', opt4: 'Раствор', correct: 2 },
  { theme: 'Строительство', word: 'Mortar', opt1: 'Бетон', opt2: 'Строительный раствор', opt3: 'Затирка', opt4: 'Шпатлёвка', correct: 2 },
  { theme: 'Строительство', word: 'Concrete', opt1: 'Раствор', opt2: 'Бетон', opt3: 'Цемент', opt4: 'Асфальт', correct: 2 },
  { theme: 'Строительство', word: 'Cement', opt1: 'Бетон', opt2: 'Цемент', opt3: 'Известь', opt4: 'Гипс', correct: 2 },
  { theme: 'Строительство', word: 'Aggregate', opt1: 'Цемент', opt2: 'Заполнитель', opt3: 'Вода', opt4: 'Пластификатор', correct: 2 },
  { theme: 'Строительство', word: 'Rebar', opt1: 'Арматурная сетка', opt2: 'Арматурный стержень', opt3: 'Закладная деталь', opt4: 'Анкер', correct: 2 },
  { theme: 'Строительство', word: 'Stirrup', opt1: 'Продольная арматура', opt2: 'Хомут', opt3: 'Шпилька', opt4: 'Анкер', correct: 2 },
  { theme: 'Строительство', word: 'Formwork', opt1: 'Опалубка', opt2: 'Леса', opt3: 'Подмости', opt4: 'Крепление', correct: 1 },
  { theme: 'Строительство', word: 'Shoring', opt1: 'Опалубка', opt2: 'Крепление стен котлована', opt3: 'Леса', opt4: 'Подпорка', correct: 2 },
  { theme: 'Строительство', word: 'Excavation', opt1: 'Земляные работы', opt2: 'Выемка грунта', opt3: 'Планировка', opt4: 'Обратная засыпка', correct: 2 },
  { theme: 'Строительство', word: 'Backfill', opt1: 'Выемка грунта', opt2: 'Обратная засыпка', opt3: 'Уплотнение', opt4: 'Планировка', correct: 2 },
  { theme: 'Строительство', word: 'Compaction', opt1: 'Засыпка', opt2: 'Уплотнение', opt3: 'Планировка', opt4: 'Выравнивание', correct: 2 },
  { theme: 'Строительство', word: 'Grading', opt1: 'Уплотнение', opt2: 'Планировка грунта', opt3: 'Выемка', opt4: 'Засыпка', correct: 2 },
  { theme: 'Строительство', word: 'Retaining wall', opt1: 'Несущая стена', opt2: 'Подпорная стена', opt3: 'Перегородка', opt4: 'Диафрагма', correct: 2 },
  { theme: 'Строительство', word: 'Load bearing wall', opt1: 'Несущая стена', opt2: 'Перегородка', opt3: 'Подпорная стена', opt4: 'Диафрагма', correct: 1 },
  { theme: 'Строительство', word: 'Partition wall', opt1: 'Несущая стена', opt2: 'Перегородка', opt3: 'Подпорная стена', opt4: 'Диафрагма', correct: 2 },
  { theme: 'Строительство', word: 'Curtain wall', opt1: 'Несущая стена', opt2: 'Навесной фасад', opt3: 'Перегородка', opt4: 'Витрина', correct: 2 },
  { theme: 'Строительство', word: 'Stud', opt1: 'Балка', opt2: 'Стойка каркаса', opt3: 'Ригель', opt4: 'Укос', correct: 2 },
  { theme: 'Строительство', word: 'Header', opt1: 'Перемычка', opt2: 'Ригель', opt3: 'Стойка', opt4: 'Обвязка', correct: 1 },
  { theme: 'Строительство', word: 'Sill plate', opt1: 'Мауэрлат', opt2: 'Нижняя обвязка', opt3: 'Верхняя обвязка', opt4: 'Лежень', correct: 2 },
  { theme: 'Строительство', word: 'Top plate', opt1: 'Нижняя обвязка', opt2: 'Верхняя обвязка', opt3: 'Мауэрлат', opt4: 'Ригель', correct: 2 },
  { theme: 'Строительство', word: 'Sheathing', opt1: 'Обшивка', opt2: 'Обрешётка', opt3: 'Опалубка', opt4: 'Настил', correct: 1 },
  { theme: 'Строительство', word: 'Subfloor', opt1: 'Чистовой пол', opt2: 'Черновой пол', opt3: 'Стяжка', opt4: 'Лаги', correct: 2 },
  { theme: 'Строительство', word: 'Underlayment', opt1: 'Черновой пол', opt2: 'Подложка', opt3: 'Стяжка', opt4: 'Настил', correct: 2 },
  { theme: 'Строительство', word: 'Screed', opt1: 'Подложка', opt2: 'Стяжка', opt3: 'Черновой пол', opt4: 'Настил', correct: 2 },
  { theme: 'Строительство', word: 'Parquet', opt1: 'Ламинат', opt2: 'Паркет', opt3: 'Линолеум', opt4: 'Плитка', correct: 2 },
  { theme: 'Строительство', word: 'Laminate flooring', opt1: 'Паркет', opt2: 'Ламинат', opt3: 'Линолеум', opt4: 'Ковролин', correct: 2 },
  { theme: 'Строительство', word: 'Linoleum', opt1: 'Паркет', opt2: 'Линолеум', opt3: 'Ламинат', opt4: 'Плитка', correct: 2 },
  { theme: 'Строительство', word: 'Tile', opt1: 'Плитка', opt2: 'Кирпич', opt3: 'Камень', opt4: 'Мозаика', correct: 1 },
  { theme: 'Строительство', word: 'Plaster', opt1: 'Шпатлёвка', opt2: 'Штукатурка', opt3: 'Затирка', opt4: 'Краска', correct: 2 },
  { theme: 'Строительство', word: 'Putty', opt1: 'Шпатлёвка', opt2: 'Штукатурка', opt3: 'Затирка', opt4: 'Грунтовка', correct: 1 },
  { theme: 'Строительство', word: 'Primer', opt1: 'Краска', opt2: 'Грунтовка', opt3: 'Шпатлёвка', opt4: 'Лак', correct: 2 },
  { theme: 'Строительство', word: 'PVC pipe', opt1: 'Металлическая труба', opt2: 'ПВХ-труба', opt3: 'Медная труба', opt4: 'Чугунная труба', correct: 2 },
  { theme: 'Строительство', word: 'Copper pipe', opt1: 'Стальная труба', opt2: 'Медная труба', opt3: 'ПВХ-труба', opt4: 'Полипропиленовая труба', correct: 2 },
  { theme: 'Строительство', word: 'Fitting', opt1: 'Фитинг', opt2: 'Арматура трубопроводная', opt3: 'Муфта', opt4: 'Переходник', correct: 1 },
  { theme: 'Строительство', word: 'Valve', opt1: 'Кран', opt2: 'Задвижка', opt3: 'Клапан', opt4: 'Вентиль', correct: 3 },
  { theme: 'Строительство', word: 'Faucet', opt1: 'Водопроводный кран', opt2: 'Клапан', opt3: 'Задвижка', opt4: 'Вентиль', correct: 1 },
  { theme: 'Строительство', word: 'Shutoff valve', opt1: 'Смеситель', opt2: 'Запорный клапан', opt3: 'Обратный клапан', opt4: 'Редуктор давления', correct: 2 },
  { theme: 'Строительство', word: 'Drain', opt1: 'Канализация', opt2: 'Слив', opt3: 'Трап', opt4: 'Сифон', correct: 2 },
  { theme: 'Строительство', word: 'Sewer', opt1: 'Водопровод', opt2: 'Канализация', opt3: 'Дренаж', opt4: 'Ливнёвка', correct: 2 },
  { theme: 'Строительство', word: 'Septic tank', opt1: 'Канализация', opt2: 'Септик', opt3: 'Дренажный колодец', opt4: 'Жироуловитель', correct: 2 },
  { theme: 'Строительство', word: 'Manhole', opt1: 'Септик', opt2: 'Смотровой колодец', opt3: 'Дренажный колодец', opt4: 'Водосборник', correct: 2 },
  { theme: 'Строительство', word: 'Duct', opt1: 'Труба', opt2: 'Воздуховод', opt3: 'Кабельный канал', opt4: 'Дымоход', correct: 2 },
  { theme: 'Строительство', word: 'Vent', opt1: 'Воздуховод', opt2: 'Вентиляционное отверстие', opt3: 'Дымоход', opt4: 'Вытяжка', correct: 2 },
  { theme: 'Строительство', word: 'Chimney', opt1: 'Вентиляция', opt2: 'Дымоход', opt3: 'Воздуховод', opt4: 'Труба', correct: 2 },
  { theme: 'Строительство', word: 'Flue', opt1: 'Дымоход', opt2: 'Дымовая труба', opt3: 'Вентиляционный канал', opt4: 'Воздухозаборник', correct: 1 },
  { theme: 'Строительство', word: 'HVAC', opt1: 'Водоснабжение и канализация', opt2: 'Отопление, вентиляция и кондиционирование', opt3: 'Электроснабжение', opt4: 'Пожаротушение', correct: 2 },
  { theme: 'Строительство', word: 'Boiler', opt1: 'Печь', opt2: 'Котёл', opt3: 'Камин', opt4: 'Теплообменник', correct: 2 },
  { theme: 'Строительство', word: 'Furnace', opt1: 'Котёл', opt2: 'Печь', opt3: 'Камин', opt4: 'Обогреватель', correct: 2 },
  { theme: 'Строительство', word: 'Radiator (heating)', opt1: 'Радиатор отопления', opt2: 'Тёплый пол', opt3: 'Конвектор', opt4: 'Тепловентилятор', correct: 1 },
  { theme: 'Строительство', word: 'Conduit', opt1: 'Кабель', opt2: 'Кабельный канал', opt3: 'Воздуховод', opt4: 'Лоток', correct: 2 },
  { theme: 'Строительство', word: 'Outlet', opt1: 'Выключатель', opt2: 'Электрическая розетка', opt3: 'Распределительная коробка', opt4: 'Светильник', correct: 2 },
  { theme: 'Строительство', word: 'Switch', opt1: 'Розетка', opt2: 'Выключатель', opt3: 'Предохранитель', opt4: 'Автомат', correct: 2 },
  { theme: 'Строительство', word: 'Junction box', opt1: 'Розетка', opt2: 'Распределительная коробка', opt3: 'Выключатель', opt4: 'Щиток', correct: 2 },
  { theme: 'Строительство', word: 'Circuit breaker panel', opt1: 'Распределительная коробка', opt2: 'Электрический щиток', opt3: 'Трансформатор', opt4: 'Счётчик', correct: 2 },
  { theme: 'Строительство', word: 'Grounding', opt1: 'Изоляция', opt2: 'Заземление', opt3: 'Фазировка', opt4: 'Экранирование', correct: 2 },
];

// ===== СОЗДАЁМ EXCEL =====
const excelData = allQuestions.map(q => ({
  'Тема': q.theme,
  'Слово/фраза для перевода': q.word,
  'Вариант 1': q.opt1,
  'Вариант 2': q.opt2,
  'Вариант 3': q.opt3,
  'Вариант 4': q.opt4,
  'Номер правильного ответа (от 1 до 4)': q.correct
}));

const ws = xlsx.utils.json_to_sheet(excelData);
const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, 'Questions');

const filePath = path.join(__dirname, 'data', 'questions.xlsx');
xlsx.writeFile(wb, filePath);

// Подсчёт по темам
const medicineCount = allQuestions.filter(q => q.theme === 'Медицина').length;
const engineeringCount = allQuestions.filter(q => q.theme === 'Инженерия').length;
const constructionCount = allQuestions.filter(q => q.theme === 'Строительство').length;

console.log(`✅ Финальный файл questions.xlsx создан!`);
console.log(`📊 Всего вопросов: ${allQuestions.length}`);
console.log(`   🏥 Медицина: ${medicineCount}`);
console.log(`   ⚙️ Инженерия: ${engineeringCount}`);
console.log(`   🏗️ Строительство: ${constructionCount}`);